USE [centro_4]
GO

/****** Object:  Table [dbo].[PACIENT]    Script Date: 11/04/2024 19:09:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PACIENT](
	[ID_PACIENT] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[LAST_NAME] [varchar](50) NOT NULL,
	[BIRTHDAY] [date] NOT NULL,
	[LOCATION] [varchar](50) NOT NULL,
	[COUNTRY] [char](5) NULL,
	[PHONE] [int] NULL,
	[EMAIL] [varchar](50) NOT NULL,
	[OBSERVATIONS] [varchar](50) NULL,
 CONSTRAINT [PK_PACIENT] PRIMARY KEY CLUSTERED 
(
	[ID_PACIENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [centro_4]
GO

/****** Object:  Table [dbo].[HISTORY]    Script Date: 12/04/2024 15:01:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HISTORY](
	[ID_HISTORY] [int] IDENTITY(1,1) NOT NULL,
	[TIMESTAMP] [datetime] NULL,
	[OBSERVATION] [varchar](2000) NULL,
 CONSTRAINT [PK_HISTORY] PRIMARY KEY CLUSTERED 
(
	[ID_HISTORY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [centro_4]
GO

/****** Object:  Table [dbo].[RECORDS]    Script Date: 12/04/2024 15:07:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RECORDS](
	[ID_HISTORY] [int] NOT NULL,
	[ID_PACIENT] [int] NOT NULL,
	[ID_DOCTOR] [int] NOT NULL,
 CONSTRAINT [PK_RECORDS] PRIMARY KEY CLUSTERED 
(
	[ID_HISTORY] ASC,
	[ID_PACIENT] ASC,
	[ID_DOCTOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [centro_4]
GO

/****** Object:  Table [dbo].[COUNTRY]    Script Date: 12/04/2024 15:11:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COUNTRY](
	[ID_COUNTRY] [char](3) NOT NULL,
	[COUNTRY] [varchar](50) NULL,
 CONSTRAINT [PK_COUNTRY] PRIMARY KEY CLUSTERED 
(
	[ID_COUNTRY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [centro_4]
GO

/****** Object:  Table [dbo].[WORK]    Script Date: 12/04/2024 15:16:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORK](
	[ID_WORK] [int] IDENTITY(1,1) NOT NULL,
	[ETL_WORK] [datetime] NULL,
	[STATUS] [smallint] NULL,
	[OBSERVACION] [varchar](1000) NULL,
 CONSTRAINT [PK_WORK] PRIMARY KEY CLUSTERED 
(
	[ID_WORK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [centro_4]
GO

/****** Object:  Table [dbo].[WORK_PACIENT]    Script Date: 12/04/2024 15:19:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORK_PACIENT](
	[ID_WORK] [int] NOT NULL,
	[ID_PACIENT] [int] NOT NULL,
	[ID_DOCTOR] [int] NOT NULL,
 CONSTRAINT [PK_WORK_PACIENT] PRIMARY KEY CLUSTERED 
(
	[ID_WORK] ASC,
	[ID_PACIENT] ASC,
	[ID_DOCTOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

